### PR TITLE
Fixes django-filer 1.* compatibility issue

### PR DESCRIPTION
**Pull request by ad-lebedev**
filermedia templatetag error

### CODE REVIEW

**Comment by ad-lebedev** [comment]
Tests for django 1.4.* have been failed because of 1f5f3b130b47236be89f328b3c06bf736f978b4e

**Comment by darklow** [comment]
I fixed the bug that caused tests to fail.
Thanks for PR.

**Comment by ad-lebedev** [comment]
Great, thanks! 
When do you plan to update PyPI repo?

**Comment by darklow** [comment]
@ad-lebedev Just released new version with the fixes `django-suit==0.2.16`

**Pull request merged**
