### PR TITLE
Added django-mail-factory template support

### PR DESCRIPTION
**Pull request by fmartingr**
+ Added needed templates
+ Using suit-tabs instead of mail-factory own javascript for multi-language support
+ Mail list/Mail form re-style to fit django-suit

### CODE REVIEW

**Comment by darklow** [comment]
I won't be including any 3rd party support in suit repository.
Separating them in other repos is the right idea.

**Comment by SalahAdDin** [comment]
i don't think that it be a good practice, it fragment all code.

**Comment by fmartingr** [comment]
> i don't think that it be a good practice, it fragment all code.

I agree that having all the suit third-party integrations in the suit repo is way more comfortable for us users (developers), but @darklow can't stay up to date with third parties he doesn't even use or know of its existence.

I'd rather prefer having suit updates more often without external interferences that having delays because some other integration with another Django app, which can evolve into more suit admin features. If I need a particular admin templates for an app I can develop them myself since is only a few HTML overwrites in most cases.

Having a wiki dedicated section in the README or the wiki for that *third-third-party* packages is better for the suit admin itself since the main developers can focus on the core rather on the sub-integrations  "needed".

**Comment by SalahAdDin** [comment]
@fmartingr Yeah man, i think same.

**Pull request closed without merging**
