### PR TITLE
Fixes for django-filer support

### PR DESCRIPTION
**Pull request by rense**
filer/templatetags/filermedia.py will be removed,
‘filer_staticmedia_prefix’ is replaced by the proper STATIC_URL now.

### CODE REVIEW

**Comment by SalahAdDin** [comment]
:+1:

**Comment by shulcsm** [comment]
Looks good, except it's not backwards compatible. What is the breaking release for filer, is it public? And imho 1.9 adjustments must be done separately.

**Comment by rense** [comment]
Didn't mean to add to this pull-request, sorry.

**Comment by chris-erickson** [comment]
Is this the only workaround for this issue with Filer?  For SEO and other people looking, this is the error I'm getting at the moment with `django-suit==0.2.15`, `django-filer==1.0.4`: 
```
TemplateSyntaxError: 'filermedia' is not a valid tag library: Template library filermedia not found
```

**Comment by ad-lebedev** [comment]
@darklow, do you have a plan to fix this problem? May be you'll accept this merge?

**Comment by darklow** [comment]
@ad-lebedev I cannot accept this merge as each commit of pull request is about something else. Some are to SVGs, some to filer, some to Django 1.9

**Comment by darklow** [comment]
Closing in favor to this PR: https://github.com/darklow/django-suit/pull/464

**Pull request closed without merging**
