### PR TITLE
ui/css: fix issue when displaying CKEditor in 'Inline'. Fix #544, Fix #268

### LINKED ISSUE #268: There seems to be a problem with embedding the CKEditor into SortableStackedInline
See image:
image

I'm trying to figure out what is wrong. Looks like a css issue? Same issue with normal StackedInlines.

Using django-suit==0.2.9 and django-suit-ckeditor==0.0.2

### LINKED ISSUE #544: suit-creditor does not work in standart inline
Django (1.10.1)
django-suit (0.2.21)
django-suit-ckeditor (0.0.2)
Python version: 3. 4

Issue: suit-creditor does not work in standart inline

Code from admin.py

```
class PartitionInline(admin.StackedInline):

    extra = 1
    model = Partition
    form = PartitionInlineAdminModelForm
    fieldsets = (
        (
            None, {
                # 'classes': ('collapse', ),
                'classes': ('full-width', ),
                'fields': (
                    'name',
                )
            }
        ),]
```

code from forms.py
```

from django.utils.translation import ugettext_lazy as _
from django import forms

from suit_ckeditor.widgets import CKEditorWidget

from apps.core.widgets import CKEditorAdminWidget


[class PartitionInlineAdminModelForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        # self.fields['name'].widget.attrs['placeholder'] = _('Enter name')
        # self.fields['name'].widget.attrs['class'] = 'span12'

    class Meta:
        widgets = {
            'name': CKEditorWidget()
        }]
```

screenshot from 2016-09-23 19 47 29

### PR DESCRIPTION
**Pull request by hasB4K**
Hi,

I have found how to solve the issues #544 and #268.
In the file `suit/static/suit/css` (and in the less file `suit/static/suit/less/ui/form.less`), there is a property that broke everything:

``` css
.form-horizontal .inline-related span {
    display: inline-block
}
```

If you remove it, everything works fine! However I didn't find a way to override it properly...
Sadly I can't figure out what the purpose of this property. So, for now, I have removed it. @darklow is that okay?

Regards,
And Merry Christmas everyone :santa: :smile:!

-- 
Mathis 'hasB4K' Felardos

### CODE REVIEW

**Comment by cl4rke** [comment]
Hi @hasB4K, this works great for ckeditor, but it will ruin the css for other inline forms. Please make the css more specific for only ckeditor 😄

**Comment by hasB4K** [comment]
@cl4rke That's the point, I didn't found any bugs for others inline forms... Do you have, at least, any exemple?

**Comment by darklow** [comment]
I haven't tested, but I changed SPAN selector into more precise one, so that it shouldn't affect anything in inlines anymore.

**Comment by darklow** [comment]
Fix included in newest v0.2.24

**Pull request closed without merging**
