### PR TITLE
fix admin/img/icon-unknown.gif at django >=1.9

### PR DESCRIPTION
**Pull request by mateuspadua**

### CODE REVIEW

**Comment by darklow** [comment]
Thank you.

**Comment by mateuspadua** [comment]
You're welcome! As a matter of fact, i should be the one thanking you!

**Comment by jordanambra** [comment]
Thanks for putting this in. I'd love to have this in a release to pypi, if you have time.

**Comment by darklow** [comment]
```
pip install django-suit==0.2.23
```

**Pull request merged**
