### PR TITLE
Fix Django 2.0 compatibility problems on v2

### PR DESCRIPTION
**Pull request by Sicilia04**

### CODE REVIEW

**Comment by abdulwahid24** [comment]
@amureki When are you planning to merge this PR? its a blocker to integrated Suit v2 on Django 2.0.

**Comment by amureki** [comment]
@abdulwahid24 I am not a django-suit contributor, just another user. :)
I guess we should ask @darklow about this.

**Comment by abdulwahid24** [comment]
Hi @darklow,
I am working on Django 2.0 and I would like to integrate Suit v2  but this PR needs to be merged in to make it compatible with Django 2.x. 
I would appreciate your help.
Thanks

**Comment by darklow** [comment]
If somebody would help testing and can approve that it supports also Django 1.9, 1.10 and 1.11. Then I can approve it. Thanks.

**Comment by abdulwahid24** [comment]
Thanks @darklow

**Pull request merged**
