### PR TITLE
Fixed url for `delete` action when `ModelAdmin.save_as = True` is used. refs to #512

### PR DESCRIPTION
**Pull request by bodja**

### CODE REVIEW

**Comment by darklow** [comment]
Have you tested your PR with older versions of Django?
Django Suit currently supports Django 1.4-1.9 versions.

**Comment by bodja** [comment]
On 1.8 it works

**Comment by bodja** [comment]
I will add a check for django version and will do another pull request

**Comment by darklow** [comment]
Thanks. FYI - There are some Django version check examples in some other templates file.

**Comment by bodja** [comment]
Done. I've tested it on django 1.8 and 1.9.

**Comment by darklow** [comment]
I think something is wrong with conditions you added.
1) If Django < 1.9
2) Django >= 1.9
3) What is this last `else` for?

**Comment by darklow** [comment]
Apparently I already were fixing issues this link when I was making Django Suit compatible for 1.9.

**Comment by darklow** [comment]
So I guess you original PR was ok. 
I was just asking about compatibility to see if you were aware we must support older versions too.
But apparently check for < 1.9 was already there.

**Comment by bodja** [comment]
Yes, I've reviewed it a moment ago and understood that next commit is stupid =) so the original one should already work.

**Comment by darklow** [comment]
In order to approve PR automatically I will need you to remove that second commit.

**Comment by bodja** [comment]
Already done.

**Pull request merged**
