### PR TITLE
django 2.0 patches for suit 0.2.25

### PR DESCRIPTION
**Pull request by jerzyk**
with fallback for all supported django versions, tested on the following versions:
2.0.2
1.11.10
1.10.8
1.9.13
1.8.18

### CODE REVIEW

**Comment by santoshray02** [comment]
Hello folks,
Is this fixed /Merged or we have to wait

**Comment by f213** [comment]
@darklow should we merge this PR?

**Comment by darklow** [comment]
@f213 @santoshray02 I need help with testing this PR and checking if it all works, including with few past Django versions. Once it is confirmed, I can merge in.

**Comment by jerzyk** [comment]
I’ve tested this PR on the Django versions mentioned in the first note of this PR. Plus there are reports from travis test - all positive.

One thing that could be problematic to someone, is that I’ve removed travis test for versions earlier than 1.8 (1.4.22, 1.5.12, 1.6.11, 1.7.11) as those are obsolete ones…

**Comment by darklow** [comment]
PR approved and available though newest 0.2.26
Thank you for PR and all the help!
https://pypi.python.org/pypi/django-suit

**Pull request merged**
